packaging_format = 2

id = "kavita"
name = "Kavita"
description.en = "Media server for your comics, manga and books"
description.fr = "Serveur multimédia pour vos bandes dessinées, mangas et livres"

version = "0.7.3.1~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
website = "www.kavitareader.com"
demo = "https://demo.kavitareader.com/"
admindoc = "https://wiki.kavitareader.com/en"
code = "https://github.com/Kareadita/Kavita"

[integration]
yunohost = ">= 11.1.19"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "300M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/kavita"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]
        [resources.sources.main]
        in_subdir = true
        amd64.url = "https://github.com/Kareadita/Kavita/releases/download/v0.7.3.1/kavita-linux-x64.tar.gz"
        amd64.sha256 = "11f654fb2ccfa08789cc810a189da60a9dcc999e5ab67bae653658e222880f19"
        arm64.url = "https://github.com/Kareadita/Kavita/releases/download/v0.7.3.1/kavita-linux-arm64.tar.gz"
        arm64.sha256 = "8db69c82e95a1cdf49fe699aa25a5020bdc703057bd63177a8410455b3a80b13"
        armhf.url = "https://github.com/Kareadita/Kavita/releases/download/v0.7.3.1/kavita-linux-arm.tar.gz"
        armhf.sha256 = "31763a23527512cfa187c7ea768a9937b581e509b4b37375f0f9e93f43a93eda"

    [resources.ports]
    main.default = 5000

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    api.url = "/api"
    api.show_tile = false
    api.protected= true
    api.allowed = ["visitors", "all_users"]
    api.auth_header = false

    hubs.url = "/hubs"
    hubs.show_tile = false
    hubs.protected= true
    hubs.auth_header = false
    hubs.allowed = ["visitors", "all_users"]

    [resources.apt]
    packages = "sqlite3"
